-- Insert sample events for testing
INSERT INTO public.events (
  title,
  date,
  venue,
  address,
  city,
  state,
  zip_code,
  event_type,
  card_types,
  organizer_name,
  organizer_id,
  description,
  max_attendees,
  entry_fee,
  vendor_table_price,
  total_tables,
  tables_available,
  is_multi_day
) VALUES 
-- Pokemon Events
(
  'Pokemon Regional Championships - Los Angeles',
  '2025-02-15',
  'Los Angeles Convention Center',
  '1201 S Figueroa St',
  'Los Angeles',
  'CA',
  '90015',
  'Tournament',
  ARRAY['Pokemon'],
  'Pokemon Company International',
  (SELECT id FROM auth.users LIMIT 1),
  'Join us for the biggest Pokemon TCG tournament on the West Coast! Regional Championships featuring multiple formats including Standard and Expanded. Top prizes include championship points and exclusive playmats.',
  500,
  25.00,
  150.00,
  50,
  35,
  true
),
(
  'Pokemon Community Cup - San Francisco',
  '2025-01-28',
  'Moscone Center West',
  '800 Howard St',
  'San Francisco',
  'CA',
  '94103',
  'Community Event',
  ARRAY['Pokemon'],
  'Bay Area Pokemon League',
  (SELECT id FROM auth.users LIMIT 1),
  'Casual Pokemon TCG event for players of all skill levels. Fun tournaments, trading opportunities, and special guest appearances. Family-friendly environment with prizes for everyone!',
  200,
  15.00,
  75.00,
  25,
  18,
  false
),
(
  'Pokemon Pre-Release Event - Journey Together',
  '2025-03-22',
  'GameStop Events Center',
  '456 Gaming Ave',
  'Seattle',
  'WA',
  '98101',
  'Pre-Release',
  ARRAY['Pokemon'],
  'Seattle Pokemon Events',
  (SELECT id FROM auth.users LIMIT 1),
  'Be among the first to play with cards from the new Journey Together expansion! Each player receives exclusive pre-release promo cards and booster packs.',
  80,
  30.00,
  100.00,
  12,
  8,
  false
),

-- Magic: The Gathering Events
(
  'Magic: The Gathering Pro Tour Qualifier',
  '2025-02-08',
  'Phoenix Convention Center',
  '100 N 3rd St',
  'Phoenix',
  'AZ',
  '85004',
  'Tournament',
  ARRAY['Magic: The Gathering'],
  'Wizards of the Coast',
  (SELECT id FROM auth.users LIMIT 1),
  'Competitive Magic tournament with qualification spots for the upcoming Pro Tour. Standard format with side events throughout the day including Draft and Commander.',
  300,
  40.00,
  200.00,
  35,
  22,
  false
),
(
  'Commander Night - Weekly Casual Play',
  '2025-01-25',
  'The Gaming Guild',
  '789 Mana Way',
  'Austin',
  'TX',
  '78701',
  'Community Event',
  ARRAY['Magic: The Gathering'],
  'Austin Magic Community',
  (SELECT id FROM auth.users LIMIT 1),
  'Weekly Commander night featuring casual multiplayer games, deck techs, and trading. New players welcome! House rules promote fun and interaction.',
  60,
  5.00,
  50.00,
  8,
  5,
  false
),

-- Multi-Game Events
(
  'Tampa Trading Card Game Convention',
  '2025-03-01',
  'Tampa Convention Center',
  '333 S Franklin St',
  'Tampa',
  'FL',
  '33602',
  'Convention',
  ARRAY['Pokemon', 'Magic: The Gathering', 'Yu-Gi-Oh!', 'Lorcana'],
  'Florida TCG Events LLC',
  (SELECT id FROM auth.users LIMIT 1),
  'Three-day trading card game convention featuring tournaments, vendors, special guests, and exclusive merchandise. Something for every TCG enthusiast!',
  1000,
  50.00,
  300.00,
  100,
  65,
  true
),
(
  'Chicago TCG Festival',
  '2025-02-22',
  'McCormick Place',
  '2301 S Lake Shore Dr',
  'Chicago',
  'IL',
  '60616',
  'Festival',
  ARRAY['Pokemon', 'Magic: The Gathering', 'Lorcana', 'One Piece'],
  'Midwest Gaming Alliance',
  (SELECT id FROM auth.users LIMIT 1),
  'Massive TCG festival with tournaments, artist signings, exclusive previews, and the largest trading floor in the Midwest. Meet top players and content creators!',
  800,
  35.00,
  250.00,
  75,
  45,
  true
),

-- Lorcana Events
(
  'Disney Lorcana Launch Party - Shimmering Skies',
  '2025-02-14',
  'Disneyland Resort',
  '1313 Disneyland Dr',
  'Anaheim',
  'CA',
  '92802',
  'Launch Party',
  ARRAY['Lorcana'],
  'Disney Events Team',
  (SELECT id FROM auth.users LIMIT 1),
  'Celebrate the launch of the new Shimmering Skies set at the most magical place on earth! Exclusive Disney location with special prizes and photo opportunities.',
  150,
  45.00,
  175.00,
  20,
  12,
  false
),

-- One Piece Events
(
  'One Piece TCG Championship - East Coast',
  '2025-03-08',
  'Javits Center',
  '429 11th Ave',
  'New York',
  'NY',
  '10001',
  'Championship',
  ARRAY['One Piece'],
  'Bandai America',
  (SELECT id FROM auth.users LIMIT 1),
  'The ultimate One Piece TCG competition on the East Coast! Top players compete for exclusive prizes and championship recognition. Special One Piece merchandise available.',
  400,
  35.00,
  180.00,
  40,
  28,
  false
),

-- Local Game Store Events
(
  'Friday Night Magic - Standard',
  '2025-01-24',
  'Comics & Games Central',
  '567 Main Street',
  'Denver',
  'CO',
  '80202',
  'Weekly Event',
  ARRAY['Magic: The Gathering'],
  'Comics & Games Central',
  (SELECT id FROM auth.users LIMIT 1),
  'Weekly Friday Night Magic featuring Standard format. Casual competitive environment with store credit prizes. Great for both new and experienced players.',
  32,
  15.00,
  60.00,
  6,
  4,
  false
),
(
  'Pokemon League Cup - Monthly Tournament',
  '2025-02-01',
  'Heroes & Villains Comics',
  '890 Hero Blvd',
  'Portland',
  'OR',
  '97201',
  'League Cup',
  ARRAY['Pokemon'],
  'Pacific Northwest Pokemon League',
  (SELECT id FROM auth.users LIMIT 1),
  'Monthly Pokemon League Cup with championship points on the line! Standard and Junior divisions available. Prizes include booster packs and exclusive playmats.',
  64,
  20.00,
  80.00,
  10,
  7,
  false
),

-- Special Format Events
(
  'Vintage Magic Tournament',
  '2025-02-29',
  'Legacy Games Lounge',
  '123 Vintage Ave',
  'Las Vegas',
  'NV',
  '89101',
  'Vintage Tournament',
  ARRAY['Magic: The Gathering'],
  'Legacy Games Events',
  (SELECT id FROM auth.users LIMIT 1),
  'Rare Vintage format tournament featuring Magic''s most powerful cards. Bring your Black Lotus and Moxes for this premium competitive experience.',
  48,
  100.00,
  300.00,
  8,
  6,
  false
),

-- Youth Events
(
  'Pokemon Junior Championship',
  '2025-02-16',
  'Youth Center Arena',
  '456 Kids Plaza',
  'Orlando',
  'FL',
  '32801',
  'Junior Championship',
  ARRAY['Pokemon'],
  'Florida Pokemon Youth League',
  (SELECT id FROM auth.users LIMIT 1),
  'Special championship event for young Pokemon trainers ages 6-12. Safe, fun environment with age-appropriate competition and lots of prizes for participation.',
  120,
  10.00,
  50.00,
  15,
  10,
  false
);

-- Add some event days for multi-day events
INSERT INTO public.event_days (
  event_id,
  day_date,
  start_time,
  end_time,
  day_number
) VALUES 
-- Tampa Trading Card Game Convention (3 days)
(
  (SELECT id FROM public.events WHERE title = 'Tampa Trading Card Game Convention'),
  '2025-03-01',
  '09:00:00',
  '22:00:00',
  1
),
(
  (SELECT id FROM public.events WHERE title = 'Tampa Trading Card Game Convention'),
  '2025-03-02',
  '09:00:00',
  '22:00:00',
  2
),
(
  (SELECT id FROM public.events WHERE title = 'Tampa Trading Card Game Convention'),
  '2025-03-03',
  '09:00:00',
  '18:00:00',
  3
),
-- Chicago TCG Festival (2 days)
(
  (SELECT id FROM public.events WHERE title = 'Chicago TCG Festival'),
  '2025-02-22',
  '10:00:00',
  '20:00:00',
  1
),
(
  (SELECT id FROM public.events WHERE title = 'Chicago TCG Festival'),
  '2025-02-23',
  '10:00:00',
  '18:00:00',
  2
),
-- Pokemon Regional Championships (2 days)
(
  (SELECT id FROM public.events WHERE title = 'Pokemon Regional Championships - Los Angeles'),
  '2025-02-15',
  '08:00:00',
  '20:00:00',
  1
),
(
  (SELECT id FROM public.events WHERE title = 'Pokemon Regional Championships - Los Angeles'),
  '2025-02-16',
  '08:00:00',
  '18:00:00',
  2
);